#!/bin/bash

if [ ! $1 ]
then
	branch=`git branch | grep \* | sed 's/^* //'`
	echo "no branch defined - using current branch '$branch'"
else
	branch=$1
fi

if ! git branch | grep $branch
then
	echo "unknown branch $branch ... exiting"
	exit 
fi

git submodule init
git submodule update

case `hostname` in
	sens-it-iv)
	cp config/java.rb.debian_etch config/java.rb
	export JAVA_HOME=/usr/lib/jvm/java-1.5.0-sun
	;;
	c64)
	cp config/java.rb.ubuntu_hardy config/java.rb
	export JAVA_HOME=/usr/lib/jvm/java-6-sun
	;;
	*)
	echo "Please update JAVA_HOME in config/java.rb and set the JAVA_HOME environment variable"
	;;
esac

haml --rails .
