#!/bin/bash

export JAVA_HOME=/usr/lib/jvm/java-1.5.0-sun
export LD_LIBRARY_PATH=/usr/local/lib
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$JAVA_HOME/jre/lib/i386:$JAVA_HOME/jre/lib/i386/client
#/var/lib/gems/1.8/bin/mongrel_rails start -p 8000 -d -e production
/var/www/rails/current/script/process/spawner -p 8000 
