#!/bin/bash

# install ruby
patchlevel=`echo $version | cut -f2 -d 'p'`
rubyversion=`echo $version | cut -f1 -d '-'`
if ! $ruby --version | grep -w $rubyversion | grep -w $patchlevel
then
	./configure --prefix=$prefix
  make
	make install
fi
